# Generated by Django 6.0.5 on 2026-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_updated_at_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
