# Generated by Django 6.0.5 on 2026-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routinghistory',
            old_name='timestamp',
            new_name='routed_at',
        ),
        migrations.AlterField(
            model_name='routinghistory',
            name='action',
            field=models.CharField(choices=[('route', 'Route'), ('ack', 'Acknowledge'), ('reject', 'Reject/No Documents Received')], max_length=20),
        ),
    ]
